package com.leomac00.MyMediaTracker.services;

import com.leomac00.MyMediaTracker.data.dtos.MediaDto;
import com.leomac00.MyMediaTracker.exceptions.ResourceNotFoundException;
import com.leomac00.MyMediaTracker.models.Media;
import com.leomac00.MyMediaTracker.models.MediaType;
import com.leomac00.MyMediaTracker.repositories.MediaRepository;
import com.leomac00.MyMediaTracker.repositories.MediaTypeRepository;
import com.leomac00.MyMediaTracker.services.common.BaseService;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class MediaService implements BaseService<MediaDto, Media> {

    @Autowired
    private MediaRepository repository;

    @Autowired
    private MediaTypeRepository mediaTypeRepository;

    private final String mediaNotFoundMessage = "Media was not found in the database";
    private final String mediaTypeNotFoundMessage = "MediaType not found";


    private Media getMediaOrElseThrow(Long id) {
        return repository.findByIdAndDeletedFalse(id).orElseThrow(() -> new ResourceNotFoundException(mediaNotFoundMessage));
    }

    public Media findById(Long id){return getMediaOrElseThrow(id);}

    @Transactional
    public Media create(MediaDto mediaDto) {
        MediaType mediaType = mediaTypeRepository.findById(mediaDto.getMediaTypeId())
                .orElseThrow(() -> new RuntimeException(mediaTypeNotFoundMessage));

        Media media = new Media(
                null, // id generated by DB
                mediaDto.getTitle(),
                mediaDto.getDescription(),
                mediaDto.getCoverUri(),
                mediaType,
                false
        );
        try{
            repository.save(media);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        return repository.save(media);
    }

    @Transactional
    public void deleteById(Long id) {
        int updated = repository.softDeleteById(id);
        if (updated == 0) {throw new EntityNotFoundException(mediaNotFoundMessage);
        }
    }

    @Transactional
    public Media update (Long id, MediaDto mediaDto) {
        Media mediaToBeUpdated = repository.findByIdAndDeletedFalse(id).orElseThrow(() -> new RuntimeException(mediaNotFoundMessage));
        MediaType mediaType = mediaTypeRepository.findByIdAndDeletedFalse(mediaDto.getMediaTypeId())
                .orElseThrow(() -> new RuntimeException(mediaTypeNotFoundMessage));

        mediaToBeUpdated.setTitle(mediaDto.getTitle());
        mediaToBeUpdated.setDescription(mediaDto.getDescription());
        mediaToBeUpdated.setCoverUri(mediaDto.getCoverUri());
        mediaToBeUpdated.setMediaType(mediaType);

        return repository.save(mediaToBeUpdated);
    }

    public List<Media> findAll() {
        return repository.findAll().stream().filter(item -> !item.getDeleted()).toList();
    }
}

