package com.leomac00.MyMediaTracker.services;

import com.leomac00.MyMediaTracker.data.dtos.MediaDto;
import com.leomac00.MyMediaTracker.exceptions.ResourceNotFoundException;
import com.leomac00.MyMediaTracker.models.Media;
import com.leomac00.MyMediaTracker.models.MediaType;
import com.leomac00.MyMediaTracker.repositories.MediaRepository;
import com.leomac00.MyMediaTracker.repositories.MediaTypeRepository;
import com.leomac00.MyMediaTracker.services.common.BaseService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class MediaService implements BaseService<MediaDto, Media> {
    @Autowired
    private MediaRepository repository;

    @Autowired
    private MediaTypeRepository mediaTypeRepository;


    public Media findById(Long id){
        return getMediaOrElseThrow(id);
    }

    private Media getMediaOrElseThrow(Long id) {
        return repository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Media was not found in the database."));
    }

    public Media create(MediaDto mediaDto) {
        MediaType mediaType = mediaTypeRepository.findById(mediaDto.getMediaTypeId())
                .orElseThrow(() -> new RuntimeException("MediaType not found"));

        Media media = new Media(
                null, // id generated by DB
                mediaDto.getTitle(),
                mediaDto.getDescription(),
                mediaDto.getCoverUri(),
                mediaType
        );

        return repository.save(media);
    }
}
