package com.leomac00.MyMediaTracker.services;

import com.leomac00.MyMediaTracker.data.dtos.MediaDto;
import com.leomac00.MyMediaTracker.data.enums.ErrorMessage;
import com.leomac00.MyMediaTracker.exceptions.ResourceNotFoundException;
import com.leomac00.MyMediaTracker.models.Media;
import com.leomac00.MyMediaTracker.models.MediaType;
import com.leomac00.MyMediaTracker.repositories.MediaRepository;
import com.leomac00.MyMediaTracker.repositories.MediaTypeRepository;
import jakarta.persistence.EntityNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional(readOnly = true)
public class MediaService {

    @Autowired
    private MediaRepository mediaRepository;

    @Autowired
    private MediaTypeRepository mediaTypeRepository;


    private Media getMediaOrElseThrow(Long id) {
        return mediaRepository.findByIdAndDeletedFalse(id).orElseThrow(() -> new ResourceNotFoundException(ErrorMessage.MEDIA_NOT_FOUND.getMessage()));
    }

    public Media findById(Long id){return getMediaOrElseThrow(id);}

    @Transactional
    public Media create(MediaDto mediaDto) {
        MediaType mediaType = mediaTypeRepository.findById(mediaDto.getMediaTypeId())
                .orElseThrow(() -> new RuntimeException(ErrorMessage.MEDIA_TYPE_NOT_FOUND.getMessage()));

        Media media = new Media(
                null, // id generated by DB
                mediaDto.getTitle(),
                mediaDto.getDescription(),
                mediaDto.getCoverUri(),
                mediaType,
                false
        );
        try{
            mediaRepository.save(media);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        return mediaRepository.save(media);
    }

    @Transactional
    public void deleteById(Long id) {
        int updated = mediaRepository.softDeleteById(id);
        if (updated == 0) {throw new EntityNotFoundException(ErrorMessage.MEDIA_NOT_FOUND.getMessage());
        }
    }

    @Transactional
    public Media update (Long id, MediaDto mediaDto) {
        Media mediaToBeUpdated = mediaRepository.findByIdAndDeletedFalse(id).orElseThrow(() -> new RuntimeException(ErrorMessage.MEDIA_NOT_FOUND.getMessage()));
        MediaType mediaType = mediaTypeRepository.findByIdAndDeletedFalse(mediaDto.getMediaTypeId())
                .orElseThrow(() -> new RuntimeException(ErrorMessage.MEDIA_TYPE_NOT_FOUND.getMessage()));

        mediaToBeUpdated.setTitle(mediaDto.getTitle());
        mediaToBeUpdated.setDescription(mediaDto.getDescription());
        mediaToBeUpdated.setCoverUri(mediaDto.getCoverUri());
        mediaToBeUpdated.setMediaType(mediaType);

        return mediaRepository.save(mediaToBeUpdated);
    }

    public List<Media> findAll() {
        return mediaRepository.findAll().stream().filter(item -> !item.getDeleted()).toList();
    }
}

