ALTER TABLE media
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE media_type
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE user_permission
ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;